module.exports.findProfile = require('./profile/findProfile')
module.exports.getProfile = require('./profile/getProfile')
module.exports.createAccessProfile = require('./profile/createAccessProfile')
module.exports.updateProfile = require('./profile/updateProfile')
module.exports.createMatch = require('./match/createMatch')
module.exports.updateMatch = require('./match/updateMatch')
module.exports.getMatch = require('./match/getMatch')
module.exports.deleteOldMatches = require('./deleteOldMatches')